'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WUCNegociacaoTotais

    '''<summary>
    '''LblTotalICMS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTotalICMS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblTotalICMSST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTotalICMSST As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblTotalIPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTotalIPI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblTotalDesconto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTotalDesconto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblTotalMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTotalMercadoria As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblTotalGeral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTotalGeral As Global.System.Web.UI.WebControls.Label
End Class
