'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WUCTEF

    '''<summary>
    '''LblErro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblErro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtCodEmitente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCodEmitente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DdlStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CbxGerarChamadoInstalacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbxGerarChamadoInstalacao As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''TxtRazaoSocial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtRazaoSocial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtCodChamadoInstalacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCodChamadoInstalacao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtCNPJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCNPJ As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtQtdPDVs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtQtdPDVs As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DdlGrupoTEF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlGrupoTEF As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TxtCodNegociacaoCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCodNegociacaoCliente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtNomeContato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNomeContato As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtBanco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtBanco As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtTelefoneContato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTelefoneContato As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtAgencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAgencia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtEmailContato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtEmailContato As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtConta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtConta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtNomeSoftwareHouse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNomeSoftwareHouse As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtContatoSoftwareHouse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtContatoSoftwareHouse As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtTelefoneSoftwareHouse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTelefoneSoftwareHouse As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CbxPinpadEnviado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbxPinpadEnviado As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''TxtEmailSoftwareHouse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtEmailSoftwareHouse As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CbxRecebeuPinpad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbxRecebeuPinpad As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''TxtNomeAplicativoComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNomeAplicativoComercial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CbxInstalado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbxInstalado As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''TxtVersaoAplicativoComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtVersaoAplicativoComercial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CbxTestado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbxTestado As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''BtnGravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnGravar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
End Class
